In [1]:
import pandas as pd
import requests
import json
import io
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.linear_model import LinearRegression

In [2]:
ideal_plant_temp = {'Lettuce':62.5, 'Lemon Grass':80,'Tulsi Basil':75}
ideal_plant_humidity = {'Lettuce':60, 'Lemon Grass':55,'Tulsi Basil':50}
ideal_plant_sunlight = {'Lettuce':4, 'Lemon Grass':5,'Tulsi Basil':7}



In [3]:
raw_content_url = 'https://raw.githubusercontent.com/JaCARYK/Weather-Application_baht/main/linear%20regression/weather_data.csv'
data = requests.get(raw_content_url)

#data = pd.read_csv('/Users/jacobkadari/Documents/GitHub/Weather-Application_baht/weather_data.csv')
#data.head()


In [4]:
x = data.drop(['Rating','Date'],axis=1).values
y= data['Rating'].values



AttributeError: 'Response' object has no attribute 'drop'

In [10]:

print(x)

[[65 45 60  8]
 [68 48 55  9]
 [70 50 50 10]
 [72 52 45 10]
 [75 55 40 11]
 [78 58 35 12]
 [80 60 30 11]
 [78 58 35 10]
 [75 55 40  9]
 [72 52 45  8]
 [70 50 50  8]
 [68 48 55  7]
 [65 45 60  7]
 [62 42 65  6]
 [60 40 70  6]
 [58 38 75  5]
 [55 35 80  5]
 [52 32 85  4]
 [50 30 90  4]
 [48 28 95  3]
 [45 25 92  3]
 [42 22 88  3]
 [40 20 85  2]
 [38 18 82  2]
 [35 15 78  2]
 [32 12 75  1]
 [30 10 72  1]
 [28  8 70  1]
 [25  6 68  1]
 [22  4 65  1]
 [20  2 62  1]]


In [11]:
print(y)

[62.73584906 62.26415094 61.32075472 59.90566038 59.43396226 58.96226415
 57.0754717  58.01886792 58.49056604 58.96226415 60.37735849 61.32075472
 62.26415094 62.73584906 64.1509434  65.09433962 66.03773585 66.50943396
 67.9245283  68.86792453 66.03773585 62.73584906 59.90566038 57.54716981
 54.24528302 50.94339623 48.58490566 46.69811321 44.33962264 41.50943396
 39.1509434 ]


In [12]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3,random_state=0)


In [13]:
from sklearn.linear_model import LinearRegression
ml=LinearRegression()
ml.fit(x_train,y_train)


LinearRegression()

In [14]:
y_pred = ml.predict(x_test)
print(y_pred)

[61.32075472 41.50943396 62.73584906 60.37735849 46.69811321 50.94339623
 59.90566038 61.32075472 66.50943396 57.54716981]


In [15]:
ml.predict([[85,75,80,10]])


array([82.54716983])

In [16]:
from sklearn.metrics import r2_score
r2_score(y_test,y_pred)


1.0

In [17]:

Ideal_Lettuce_Score = ml.predict([[65,60,60,4]])
Ideal_LemonGrass_Score= ml.predict([[85,75,55,5]])
Ideal_TulsiBasil_Score= ml.predict([[80,70,50,7]])

print('Lettuce Base Score:',Ideal_Lettuce_Score[0])
print('Lemon Grass Base Score:',Ideal_LemonGrass_Score[0])
print('Lettuce Tulsi Basil Score:',Ideal_TulsiBasil_Score[0])

ml.predict([[85,75,80,10]])
one=ml.predict([[58,52,90,1]])
two=ml.predict([[60,48,87,2]])
three=ml.predict([[61,50,83,5]])
four=ml.predict([[56,50,90,2]])
five=ml.predict([[62,50,88,1]])
six=ml.predict([[64,50,78,2]])
sevin=ml.predict([[68,49,68,1]])
eight=ml.predict([[71,50,66,4]])
Nine=ml.predict([[69,49,68,6]])
ten=ml.predict([[70,49,75,2]])

class final_percent():
    def init(self, temp_percent):
        self.temp_percent=temp_percent
    def score(self):
        return Ideal_Lettuce_Score/self.temp_percent, Ideal_LemonGrass_Score/self.temp_percent, Ideal_TulsiBasil_Score/self.temp_percent





Lettuce Base Score: 60.84905662344657
Lemon Grass Base Score: 68.39622642764294
Lettuce Tulsi Basil Score: 64.6226415221305


In [ ]:
temphigh=#csv file data for today
lowtemp=
humidity=
sunlight=

ml.predict([temphigh,lowtemp,humidity,sunlight])